import {test,expect,type Page} from '@playwright/test';
import fs from 'node:fs';
import {StandardCreateControlsFlow} from '../../flows/product-center/item-216/standard-create-controls.flow';
import type {StandardCreateControlsPage} from '../../pages/product-management/item/standard-create-controls.page';
import {buildCreateControlsSourceName} from '../../test-data/product-center/create-controls';
import {consumeExecutableOperationReceipts} from '../../utils/executable-operation-receipt';
import {fingerprintProductCenterItemImplementation} from '../../adapters/product-center/product-center-item-implementation';
import {partitionProductCenterItemSpecs,createControlsSpecPath} from '../../adapters/product-center/product-center-item-create-controls-specs';
function setup(options:{descriptionLength?:number;target?:string;disabled?:boolean;readError?:boolean;closeError?:boolean}={}){
  let restored=false,closed=false;
  const screenshot=async()=>Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lN8AAAAASUVORK5CYII=','base64');
  const page={url:()=> 'https://synthetic.invalid/pp/brand/create/standard'} as Page;
  const controls={fillDescription:async()=>{},appendDescriptionCharacter:async()=>{},readDescription:async()=>{if(options.readError)throw Error('synthetic-locator-error');return {initialLength:250,finalLength:options.descriptionLength??250,maxlength:'250',counterText:'250 / 250'};},selectMulti:async()=>{},readWeight:async()=>({multiChecked:true,disabled:options.disabled??true,visible:true,disabledStyle:true}),openSpecificationCreate:async()=>({route:options.target??'/pp/brand/spec/create',basicHeading:true,groupHeading:true,nameLabel:true}),failureScreenshot:screenshot,closeCreatedPages:async()=>{closed=true;if(options.closeError)throw Error('synthetic-popup-close-error');}} as unknown as StandardCreateControlsPage;
  return {flow:new StandardCreateControlsFlow(page,controls,async()=>({uniqueName:{exactCount:0}}),async()=>{restored=true;}),restored:()=>restored,closed:()=>closed};
}
for(const [id,operations]of [['TC-ITEM-STD-045',3],['TC-ITEM-STD-048',2],['TC-ITEM-STD-049',2]] as const)test(`正式步骤收据完整且恢复：${id}`,async({},info)=>{const s=setup();await s.flow.execute(id);expect(s.flow.assertions).toHaveLength(1);expect(s.flow.assertions[0].status).toBe('verified');expect(s.closed()&&s.restored()&&s.flow.stateRestored).toBe(true);expect(consumeExecutableOperationReceipts(info.testId).filter(r=>r.operationKey.startsWith(id+':action-'))).toHaveLength(operations);});
for(const [id,options]of [['TC-ITEM-STD-045',{descriptionLength:251}],['TC-ITEM-STD-048',{target:'/unrelated/create'}],['TC-ITEM-STD-049',{disabled:false}]] as const)test(`不匹配不能通过且恢复：${id}`,async()=>{const s=setup(options);await expect(s.flow.execute(id)).rejects.toThrow('正式断言不匹配');expect(s.flow.assertions[0].status).toBe('observed-mismatch');expect(s.restored()).toBe(true);});
test('定位异常保持证据缺口，不生成通过断言',async()=>{const s=setup({readError:true});await expect(s.flow.execute('TC-ITEM-STD-045')).rejects.toThrow('synthetic-locator-error');expect(s.flow.assertions).toHaveLength(0);expect(s.restored()).toBe(true);});
test('新窗口清理失败仍尝试主页面恢复但不能宣称全部恢复',async()=>{const s=setup({closeError:true});await expect(s.flow.execute('TC-ITEM-STD-048')).rejects.toThrow('synthetic-popup-close-error');expect(s.restored()).toBe(true);expect(s.flow.stateRestored).toBe(false);});
test('来源名称保留正式原文，不把历史500名称改成250；049不添加名称前置',()=>{expect(buildCreateControlsSourceName('TC-ITEM-STD-045',123)).toBe('标准商品-商品描述达到500字符后输入框不可继续录-123');expect(buildCreateControlsSourceName('TC-ITEM-STD-048',123)).toBe('商品-多规格商品点击去创建可跳转规格组新增页-123');expect(buildCreateControlsSourceName('TC-ITEM-STD-049',123)).toBeUndefined();});
test('十二条已合格实现指纹保持',()=>{const before=JSON.parse(fs.readFileSync('deliverables/system-test-platform/standard-create-controls-prior-fingerprints.json','utf8'));expect(Object.keys(before)).toHaveLength(12);for(const[id,hash]of Object.entries(before))expect(fingerprintProductCenterItemImplementation(process.cwd(),id)).toBe(hash);});
test('新增三条与既有路由完整分区，重复选择硬阻断',()=>{const ids=['TC-ITEM-STD-045','TC-ITEM-STD-048','TC-ITEM-STD-049','TC-ITEM-STD-041','TC-ITEM-STD-005','TC-ITEM-STD-019','TC-ITEM-STD-030','TC-ITEM-STD-063','TC-ITEM-ADD-005'],routes=partitionProductCenterItemSpecs(ids);expect(routes.flatMap(r=>r.caseIds).sort()).toEqual([...ids].sort());expect(routes.find(r=>r.specPath===createControlsSpecPath)?.caseIds).toEqual(ids.slice(0,3));expect(()=>partitionProductCenterItemSpecs([ids[0],ids[0]])).toThrow('ITEM_SPEC_DUPLICATE_SELECTION');});
